#!/bin/bash

PYTHON="python3"

export INSTALL_DIR=$(readlink -f $(dirname "${BASH_SOURCE[0]}"))

UPGRADE_CMD=`$INSTALL_DIR/install_utils/get_upgrade_cmd`
INSTALL_CMD=`$INSTALL_DIR/install_utils/get_install_cmd`

if [ -z "$UPGRADE_CMD" ] || [ -z "$INSTALL_CMD" ]
then
  exit
fi

if ! command -v $PYTHON &> /dev/null
then
  echo "$PYTHON not found"
  $UPGRADE_CMD
  $INSTALL_CMD $PYTHON
fi
echo "Using `$PYTHON --version` "

$INSTALL_DIR/install_utils/install_all.py
$INSTALL_DIR/install_utils/config_all.py

unset INSTALL_DIR

echo ""
read -p "Done. Press any key to continue..."
reset
