#!/bin/bash
python="python3"
install_cmd=`install_utils/get_install_cmd`
if ! command -v $python &> /dev/null
then
  echo "$python not found"
  sudo $install_cmd $python
else
  $python --version
fi
install_utils/install_all.py
