#!/bin/bash
distro=`$(dirname "${BASH_SOURCE[0]}")/get_distro`
case $distro in
  ubuntu|debian) cmd="sudo apt-get install" ;;
  centos) cmd="sudo yum install" ;;
  manjarolinux) cmd="sudo pacman --noconfirm -S" ;;
  "") echo "could not get distro"; exit 1 ;;
  *) echo "$distro not supported"; exit 1 ;;
esac
echo $cmd
