#!/bin/bash
distro=`$(dirname "${BASH_SOURCE[0]}")/get_distro`
case $distro in
  ubuntu|debian|zorinos) cmd="sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y" ;;
# centos|centosstream) cmd="sudo yum -y update" ;;
  manjarolinux) cmd="sudo rm /var/lib/pacman/db.lck >& /dev/null; sudo pacman --noconfirm -Syu" ;;
  "") echo "could not get distro" 1>&2 ;;
  *) echo "$distro not supported" 1>&2 ;;
esac
echo $cmd
