#!/bin/bash
distro=`$(dirname "${BASH_SOURCE[0]}")/get_distro`
case $distro in
  ubuntu|debian|zorinos) cmd="sudo apt-get -y install" ;;
# centos|centosstream) cmd="sudo yum -y install" ;;
  manjarolinux) cmd="sudo pacman --noconfirm -S" ;;
  "") echo "could not get distro" 1>&2 ;;
  *) echo "$distro not supported" 1>&2 ;;
esac
echo $cmd
